name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
  docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: '1'
      REPO: ghcr.io/${{ github.repository_owner }}/hako-server
    steps:
      - uses: actions/checkout@v2
      - name: Login to registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Run docker build
        run: docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from ${REPO}:builder -t hako-server .
      - name: Cache build stage
        run: |
          docker build --build-arg BUILDKIT_INLINE_CACHE=1 -t ${REPO}:builder --target builder .
          docker push ${REPO}:builder
